### ISSUE TITLE
cannot boot any of stable version followed by guide on XDA topic

### ISSUE THREAD

**Issue by rocky57** [MontanaDevelopment/issues#10]
TWRP 3.4.0.1
XT1794
I followed guide from OP on XDA, but I am still not able to see even decryption screen (to enter decryption password).
I am attaching logcat
[console-ramoops.txt](https://github.com/MontanaDevelopment/issues/files/5249171/console-ramoops.txt)
[dmesg.log](https://github.com/MontanaDevelopment/issues/files/5249172/dmesg.log)

**Comment by JarlPenguin** [comment]
Please use an issue template
