### ISSUE TITLE
issue : broken audio

### ISSUE THREAD

**Issue by vijithmv916** [MontanaDevelopment/issues#11]
happens when i use whatsapp or google meet

using :LineageOS 16.0 v1.1

[meet-logcat.txt](https://github.com/MontanaDevelopment/issues/files/5249397/meet-logcat.txt)
[whatsapp call logcat.txt](https://github.com/MontanaDevelopment/issues/files/5249402/whatsapp.call.logcat.txt)

**Comment by JarlPenguin** [comment]
Please use an issue template
