### ISSUE TITLE
[BUG][XT1234][01/01/1970] GPS Bug / don't work

### ISSUE THREAD

**Issue by Drakon212** [MontanaDevelopment/issues#13]
Very recently I installed a new rom, the lineageos 17.1 that is here on the forum and good the rom is being very good for me, but today I needed to use uber to go to a place but the GPS just didn't work anywhere, either by the browser, be it in applications similar to uber, waze, etc.
I never had this problem before when using the factory rom, but I would like to know if you have any solution to fix this, because I really don't want to go back to the factory rom, because after a while my cell phone locks up too much.

![image](https://user-images.githubusercontent.com/75037163/100260742-8b779780-2f28-11eb-8731-e9ed6b11f43a.png)

![image](https://user-images.githubusercontent.com/75037163/100260772-94686900-2f28-11eb-9cc1-6eec4f54cf8c.png)

**Comment by JarlPenguin** [comment]
Please use the issue template

**Comment by Drakon212** [comment]
sorry but, how i create a issue template?
