### ISSUE TITLE
[BUG][XT1792][28/11/2020] GPS dont work in any apps or browser

### ISSUE THREAD

**Issue by Drakon212** [MontanaDevelopment/issues#15]
**Describe the bug**
the gps is not working in any application or browser, or when it works it throws me in a totally random place in another country

**To Reproduce**
1. Go to "Waze or Uber"
2. Look  'the location will be as invalid'

**Expected behavior**

**Logs**
https://drive.google.com/file/d/1ot-LHl7y3921EYtj7qbas-6b6O23Ovfj/view?usp=sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/75037163/100262686-4143e580-2f2b-11eb-8c32-e933762ace4d.png)
![image](https://user-images.githubusercontent.com/75037163/100262696-45700300-2f2b-11eb-99d2-63c84cbfa77a.png)

**Build info (please complete the following information):**
 - Lineage OS 17.1 v1.10
 - Product SKU XT1792

**Comment by JarlPenguin** [comment]
Attach logs, then I will reopen this issue

**Comment by Drakon212** [comment]
I only have this log on the entire phone, there is no log cat or anything like that ..

**Comment by Drakon212** [comment]
Updated the log, now I believe it is correct! @JarlPenguin
