### ISSUE TITLE
[BUG][XT1972][12/04/2020] GPS dont work in any apps or browser

### ISSUE THREAD

**Issue by Drakon212** [MontanaDevelopment/issues#16]
**Describe the bug**
the gps is not working in any application or browser, or when it works it throws me in a totally random place in another country

**To Reproduce**
1. Go to "Waze or Uber"
2. Look  'the location will be as invalid'

**Expected behavior**

**Logs**
https://drive.google.com/file/d/1DVabmn-EYOGneG0NNBVSHUe8UdbaPYyR/view?usp=sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/75037163/100262686-4143e580-2f2b-11eb-8c32-e933762ace4d.png)
![image](https://user-images.githubusercontent.com/75037163/100262696-45700300-2f2b-11eb-99d2-63c84cbfa77a.png)

**Build info (please complete the following information):**
 - Lineage OS 17.1 v1.10
 - Product SKU XT1792

**Comment by JarlPenguin** [comment]
Do you have the latest firmware from stock installed?

**Comment by Drakon212** [comment]
Yes, as far as I know, I always kept everything up to date on my cell phone, the last thing I did on it was to put this personalized rom.

**Comment by Drakon212** [comment]
> Do you have the latest firmware from stock installed?
Yes, I always kept everything up to date on my cell phone, the last thing I did was put this personalized rom on.

**Comment by JarlPenguin** [comment]
Does the GPS work in other ROMs?

**Comment by Drakon212** [comment]
> Does the GPS work in other ROMs?
It always worked normally on the original Motorola ROM I never had any problems, this is the first custom rom I install on my phone and it has this problem

**Comment by Drakon212** [comment]
@JarlPenguin Will there be any updates in the rom to fix this?

**Comment by JarlPenguin** [comment]
@Drakon212 we're unable to reproduce this, I will try though.
