### ISSUE TITLE
[BUG][XT1795][06/12/2020] Google camera crashes

### ISSUE THREAD

**Issue by vijithmv916** [MontanaDevelopment/issues#17]
**Describe the bug**
Google camera is crashing after i take photos, especially at taking night sight mode,
then only works after device reboot

**To Reproduce**
1. Go to 'Google Camera app'
2. Scroll to 'night sight'
3. Snap photo

**Expected behavior**
expect to archive [stability]

**Logs**
[gc_log_.txt](https://github.com/MontanaDevelopment/issues/files/5648529/gc_log_.txt)

**Screenshots**

**Build info (please complete the following information):**
 - Version LOS17.1 v1.10
 - Product SKU XT1795

**Comment by JarlPenguin** [comment]
Google Camera isn't supported, please use actual apps that can be downloaded from the Play Store.
