### ISSUE TITLE
[BUG][XT1792] The power off and restart buttons do not appear when I hold the power button.

### ISSUE THREAD

**Issue by ghost** [MontanaDevelopment/issues#19]
**Describe the bug**
The power off and restart buttons do not appear when I hold the power button.
  ###
**To Reproduce**
Hold the power button.

**Expected behavior**
The virtual power off and restart buttons appear.

**Build info (please complete the following information):**
 - Version [aosp_montana-userdebug 12 SP1A.210812.016.A1 eng.kiam00.20211028.121147 dev-keys]
 - Product SKU [XT1792]

**Additional context**
This happened on AOSP 12.

**Comment by JarlPenguin** [comment]
On Android 12 you need to press Volume Up + Power for the power menu to appear.
