### ISSUE TITLE
[BUG][XT1790][09/13/2020] Failed to apply optimization

### ISSUE THREAD

**Issue by CypherNoodle** [MontanaDevelopment/issues#9]
**Describe the bug**
Logcat Reader spam failed to apply optimization and failed to read /sys/devices/system/cpu/cpu0

**To Reproduce**
1. Go to Logcat Reader or catlog
2. Click on screens or touch anywere 
3. See error

**Expected behavior**

**Logs**
https://drive.google.com/file/d/10OrexFnOWGGxeCdsbpbG8uVFM0hWkYII/view?usp=drivesdk

**Build info (please complete the following information):**
 - Version LOS17.1 v1.2
 - Product SKU xt 1790

**Comment by JarlPenguin** [comment]
Partially fixed, remaining error is a wontfix
